name:                FP-HASKELL
version:             0.1.0.0
github:              "githubuser/FP-HASKELL"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Bật cờ -threaded để chạy song song (parallel)
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

# Dependencies chung
dependencies:
- base >= 4.7 && < 5

# --- 1. THƯ VIỆN (Code chung ở 'src') ---
library:
  source-dirs: src
  exposed-modules:
  - Types
  - Render
  - GameLogic
  dependencies:
    # Dependencies cho các tệp trong 'src'
    - aeson
    - gloss
    - random
    - parallel
    - containers  # <-- MỚI: Thêm `containers` cho BFS

# --- 2. TỆP THỰC THI (Tách biệt) ---
executables:
  
  # --- SERVER ---
  bomberman-server:
    main:                Server.hs
    source-dirs:         app/server
    dependencies:
    - FP-HASKELL    # Thư viện (Types, Render, GameLogic)
    - network
    - aeson
    - bytestring
    - stm
    - random
    - containers  # Đã thêm ở lần trước

  # --- CLIENT ---
  bomberman-client:
    main:                NetworkedMain.hs
    source-dirs:         app/client
    dependencies:
    - FP-HASKELL
    - gloss
    - network
    - aeson
    - bytestring