name:                FP-HASKELL
version:             0.1.0.0
github:              "githubuser/FP-HASKELL"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

#threaded (parallel)
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Types
  - Render
  - GameLogic
  dependencies:
    - aeson
    - gloss
    - random
    - parallel
    - containers 

executables:
  bomberman-server:
    main:                Server.hs
    source-dirs:         app/server
    dependencies:
    - FP-HASKELL   
    - network
    - aeson
    - bytestring
    - stm
    - random
    - containers 

  bomberman-client:
    main:                NetworkedMain.hs
    source-dirs:         app/client  
    dependencies:
    - FP-HASKELL
    - gloss
    - network
    - aeson
    - bytestring
    - containers