name:                FP-HASKELL
version:             0.1.0.0
author:              "UEH Team"
maintainer:          "you@example.com"
license:             BSD3
extra-source-files:  []

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - ansi-terminal
    - stm
    - random
    - parallel
    - network
    - brick
    - gloss
    - aeson
    - bytestring
    

executables:
  FP-HASKELL-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - FP-HASKELL
      - base >= 4.7 && < 5
      - ansi-terminal
      - stm
      - random
      - parallel
      - network
      - brick
      - gloss
      - aeson
      - bytestring  
